=== natowi/rti-chi/components/RTIbuilder/XMLcarrier/src/XMLcarrier/lptracker.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://alba.di.uminho.pt/XMLCarrier" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xc="http://alba.di.uminho.pt/XMLCarrier" 
    xmlns:xlink="http://www.w3.org/1999/xlink"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:import namespace="http://www.w3.org/1999/xlink"
        schemaLocation="xlink.xsd"/>
   
    <xs:element name="XMLCarrier" xmlns:xc="http://alba.di.uminho.pt/XMLCarrier">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Header">
                <xs:complexType>
                    <xs:sequence minOccurs="0">
                        <xs:element name="ProjectName" type="xs:string" />
                        <xs:element name="Description" type="xs:string" />
                        <xs:element name="Author" type="xs:string" />
                        <xs:element name="CreationDate" type="xs:string" />
                        <xs:element name="LastModificationDate" type="xs:string" />
                        <xs:element name="UserInfo" type="xs:string" />
                        <xs:element name="Host" type="xs:string" />
                        <xs:element name="AdditionalInfo">
                            <xs:complexType>
                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                    <xs:element name="Info" minOccurs="0" maxOccurs="1">
                                        <xs:complexType>
                                            <xs:attribute name="OperatingSystem" use="optional"></xs:attribute>
                                            <xs:attribute name="MemoryAvailable" use="optional"></xs:attribute>
                                            <xs:attribute name="Processor" use="optional"></xs:attribute>
                                            <xs:attribute name="MacAddress" use="optional"></xs:attribute>
                                        </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Info2" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="NAME"/>
                                                <xs:attribute name="VALUE"/>
                                            </xs:complexType>
                                         </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="UUID" />
                </xs:complexType>
            </xs:element>
        <xs:element name="FileSec">
            <xs:complexType>
                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="fileList">
                        <xs:complexType>
                            <xs:sequence maxOccurs="unbounded">
                                <xs:element name="fileInfo">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="fileLink">
                                                <xs:complexType>
                                                    <xs:attribute ref="xlink:href"/>
                                                    <xs:attribute name="LOCTYPE" type="xs:string" />
                                                    <xs:attribute name="CHECKSUM" type="xs:string" />
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                <xs:attribute name="UUID" />
                                <xs:attribute name="MIMETYPE" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>            
                </xs:complexType>
            </xs:element>
            <xs:element name="fileGrp" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="fileRef"/>
                    </xs:sequence>
                    <xs:attribute name="UUID" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
      </xs:complexType>
        </xs:element>
            <xs:element name="Processes">
    <xs:complexType>
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="process">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="description" />
                                <xs:sequence>
                                    <xs:element name="Input">
                                        <xs:complexType>
                                            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                <xs:element name="ref" />
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="Output">
                                        <xs:complexType>
                                            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                <xs:element name="ref" />
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                    </xs:sequence>
                    <xs:attribute name="COMPID" />
                    <xs:attribute name="ID" />
                    <xs:attribute name="TYPE" />
                    <xs:attribute name="STATUS" />
                    <xs:attribute name="SEQ" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
            </xs:element>
    <xs:element name="dataSec">
    <xs:complexType>
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Data" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="description"/>
                        <xs:element name="param" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="value" />
                                </xs:sequence>
                                <xs:attribute name="TYPE" />
                                <xs:attribute name="NAME" />
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="area" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="BEGIN" type="xs:string" use="optional"/>
                                <xs:attribute name="COORDS" type="xs:string" use="optional" />
                                <xs:attribute name="END" type="xs:string" use="optional"/>
                                <xs:attribute name="SHAPE" type="xs:string" use="optional"/>
                                <xs:attribute name="UUID" type="xs:string" use="optional" />
                                <xs:attribute name="algorithm" type="xs:string" use="optional" />
                                <xs:attribute name="binarize" type="xs:string" use="optional" />
                                <xs:attribute name="fileGrpID" type="xs:string" use="optional" />
                                <xs:attribute name="hough" type="xs:string" use="optional" />
                                <xs:attribute name="projectName" type="xs:string" use="optional" />
                                <xs:attribute name="projectPath" type="xs:string" use="optional" />
                                <xs:attribute name="scaleFactor" type="xs:string" use="optional" />
                                <xs:attribute name="EdgeID" type="xs:string" use="optional" />
                                <xs:attribute name="MedianID" type="xs:string" use="optional" />
                                <xs:attribute name="r" type="xs:string" use="optional" />
                                <xs:attribute name="x" type="xs:string" use="optional" />
                                <xs:attribute name="y" type="xs:string" use="optional" />
                                <xs:attribute name="threshold" type="xs:string" use="optional" />
                                <xs:attribute name="BlendID" type="xs:string" use="optional" />
                                <xs:attribute name="Ref_HighLights" type="xs:string" use="optional" />
                                <xs:attribute name="Ref_LightPositions" type="xs:string" use="optional" />
                                <xs:attribute name="bd_r" type="xs:string" use="optional" />
                                <xs:attribute name="bd_x" type="xs:string" use="optional" />
                                <xs:attribute name="bd_y" type="xs:string" use="optional" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>	
                    <xs:attribute name="UUID" />
                    <xs:attribute name="NAME" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
                </xs:element>
            </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:schema>

=== natowi/rti-chi/components/RTIbuilder/RTIbuilder/blank.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<XMLCarrier xmlns="http://alba.di.uminho.pt/XMLCarrier" xmlns:xc="http://alba.di.uminho.pt/XMLCarrier" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://alba.di.uminho.pt/XMLCarrier lptracker.xsd">
    <xc:Header UUID="c18555bd-fac3-4549-802b-6692694d2904">
        <xc:ProjectName>blank</xc:ProjectName>
        <xc:Description/>
        <xc:Author>rcosta</xc:Author>
        <xc:CreationDate>2010/2/27 1:56:48</xc:CreationDate>
        <xc:LastModificationDate>2010/2/27 1:56:48</xc:LastModificationDate>
        <xc:UserInfo>rcosta</xc:UserInfo>
        <xc:Host>scratx-laptop</xc:Host>
        <xc:Timestamp>1</xc:Timestamp>
        <xc:AdditionalInfo>
            <xc:Info MacAddress="" MemoryAvailable="13234176" OperatingSystem="Windows Vista x86" Processor="2"/>
        </xc:AdditionalInfo>
    </xc:Header>
    <xc:fileSec/>
    <xc:Processes>
        <xc:process COMPID="9e275ec5-51a0-4ed2-afe3-c7ef08a8075d" ID="f32fd602-f0fd-4c47-905d-9db4a6a38b3e" SEQ="1" STATUS="NONE" TYPE="PIPELINE">
            <xc:description/>
            <xc:Input/>
            <xc:Output/>
        </xc:process>
        <xc:process COMPID="d6b14f9e-343f-4ea0-a11c-fb70c41fab64" ID="04a9d477-ce60-4ffb-a0b6-da8446de6147" SEQ="2" STATUS="NONE" TYPE="PIPELINE">
            <xc:description/>
            <xc:Input/>
            <xc:Output/>
        </xc:process>
        <xc:process COMPID="7169813b-ef73-4ca9-a405-75b14e6ee55e" ID="71ebd2f2-3763-49f4-8367-fe561360b20a" SEQ="3" STATUS="NONE" TYPE="PIPELINE">
            <xc:description/>
            <xc:Input/>
            <xc:Output/>
        </xc:process>
        <xc:process COMPID="1bcfa75b-b90a-469a-b3fa-d232431edba1" ID="4b8a1b1b-5841-4448-bb1d-c97d455fbcd8" SEQ="4" STATUS="NONE" TYPE="PIPELINE">
            <xc:description/>
            <xc:Input/>
            <xc:Output/>
        </xc:process>
    </xc:Processes>
    <xc:dataSec/>
    <xc:computedData/>
    <xc:Log/>
</XMLCarrier>

=== natowi/rti-chi/components/RTIbuilder/RTIbuilder/empty.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<XMLCarrier xmlns="http://alba.di.uminho.pt/XMLCarrier" xmlns:xc="http://alba.di.uminho.pt/XMLCarrier" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://alba.di.uminho.pt/XMLCarrier lptracker.xsd">
    <xc:Header UUID="7bf3eef3-357a-4237-8fb2-9bdd91051437">
        <xc:ProjectName>empty</xc:ProjectName>
        <xc:Description/>
        <xc:Author>rcosta</xc:Author>
        <xc:CreationDate>2010/7/8 22:23:30</xc:CreationDate>
        <xc:LastModificationDate>2010/7/8 22:23:30</xc:LastModificationDate>
        <xc:UserInfo>rcosta</xc:UserInfo>
        <xc:Host>rcosta-laptop</xc:Host>
        <xc:Timestamp>1</xc:Timestamp>
        <xc:AdditionalInfo>
            <xc:Info MacAddress="" MemoryAvailable="96272384" OperatingSystem="Windows 7 amd64" Processor="8"/>
        </xc:AdditionalInfo>
    </xc:Header>
    <xc:fileSec/>
    <xc:Processes>
        <xc:process COMPID="9e275ec5-51a0-4ed2-afe3-c7ef08a8075d" ID="892dca95-a28b-441b-aefe-d1e9a9322cc4" SEQ="1" STATUS="NONE" TYPE="PIPELINE">
            <xc:description/>
            <xc:Input/>
            <xc:Output/>
        </xc:process>
        <xc:process COMPID="d6b14f9e-343f-4ea0-a11c-fb70c41fab64" ID="5bd021d9-627b-4cd5-ab87-fe8ed31f922a" SEQ="2" STATUS="NONE" TYPE="PIPELINE">
            <xc:description/>
            <xc:Input/>
            <xc:Output/>
        </xc:process>
        <xc:process COMPID="7169813b-ef73-4ca9-a405-75b14e6ee55e" ID="9f3b94d6-5aac-4fc0-a29b-2ab18290b340" SEQ="3" STATUS="NONE" TYPE="PIPELINE">
            <xc:description/>
            <xc:Input/>
            <xc:Output/>
        </xc:process>
        <xc:process COMPID="1bcfa75b-b90a-469a-b3fa-d232431edba1" ID="f950d2fc-8108-4eca-a83d-39a03c731896" SEQ="4" STATUS="NONE" TYPE="PIPELINE">
            <xc:description/>
            <xc:Input/>
            <xc:Output/>
        </xc:process>
    </xc:Processes>
    <xc:dataSec/>
    <xc:computedData/>
    <xc:Log/>
</XMLCarrier>
